use ares_core::{AuditReport, Finding, Severity};

/// Generate a Markdown audit report.
pub fn generate_markdown(report: &AuditReport) -> String {
    let mut md = String::from("# ARES V3 Security Audit Report\n\n");
    md.push_str(&format!("**Target:** `{}`\n\n", report.target.name));
    md.push_str(&format!("**Date:** {}\n\n", report.metadata.generated_at));
    md.push_str(&format!(
        "**ARES Version:** {}\n\n",
        report.metadata.ares_version
    ));
    md.push_str(&format!(
        "**Duration:** {} seconds\n\n",
        report.metadata.scan_duration_secs
    ));
    md.push_str(&format!(
        "**Pipeline:** {}\n\n",
        report.metadata.agent_pipeline.join(" -> ")
    ));

    md.push_str("## Summary\n\n");
    md.push_str("| Severity | Count |\n");
    md.push_str("|----------|-------|\n");
    md.push_str(&format!(
        "| Critical | {} |\n",
        report.summary.critical_count
    ));
    md.push_str(&format!("| High     | {} |\n", report.summary.high_count));
    md.push_str(&format!("| Medium   | {} |\n", report.summary.medium_count));
    md.push_str(&format!("| Low      | {} |\n", report.summary.low_count));
    md.push_str(&format!(
        "| Info     | {} |\n\n",
        report.summary.informational_count
    ));

    let total_sol = report.summary.total_economic_impact_lamports as f64 / 1_000_000_000.0;
    let max_sol = report.summary.max_single_exploit_lamports as f64 / 1_000_000_000.0;
    md.push_str("## Economic Impact Estimate\n\n");
    md.push_str("| Metric | Value |\n");
    md.push_str("|--------|-------|\n");
    md.push_str(&format!(
        "| Total Extractable Value | {:.4} SOL |\n",
        total_sol
    ));
    md.push_str(&format!("| Max Single Exploit | {:.4} SOL |\n\n", max_sol));

    md.push_str("## Findings\n\n");

    for (i, finding) in report.findings.iter().enumerate() {
        md.push_str(&format!(
            "### {}. {} [{}]\n\n",
            i + 1,
            finding.title,
            finding.severity
        ));
        md.push_str(&format!("**ID:** `{}`\n\n", finding.id));
        md.push_str(&format!("**Category:** {}\n\n", finding.category));
        md.push_str(&format!(
            "**Confidence:** {:.0}%\n\n",
            finding.confidence * 100.0
        ));
        let exploit_lamports = estimate_exploit_value(finding);
        let exploit_sol = exploit_lamports as f64 / 1_000_000_000.0;
        md.push_str(&format!(
            "**Estimated Extractable Value:** {:.4} SOL\n\n",
            exploit_sol
        ));
        md.push_str(&format!("**Description:**\n{}\n\n", finding.description));

        if let Some(ref poc) = finding.proof_of_concept {
            md.push_str(&format!("**Proof of Concept:** `{:?}`\n\n", poc));
        }

        md.push_str(&format!(
            "**Recommendation:**\n{}\n\n",
            finding.recommendation
        ));

        if !finding.references.is_empty() {
            md.push_str("**References:**\n");
            for r in &finding.references {
                md.push_str(&format!("- {}\n", r));
            }
            md.push('\n');
        }

        md.push_str("---\n\n");
    }

    md.push_str("## Tools Used\n\n");
    for tool in &report.metadata.tools_used {
        md.push_str(&format!("- {}\n", tool));
    }
    md.push_str("\n---\n\n*Generated by ARES V3 — Autonomous Solana Security Auditor*\n");

    md
}

/// Generate an HTML audit report.
pub fn generate_html(report: &AuditReport) -> String {
    let md = generate_markdown(report);
    let html_body = md
        .replace("# ", "<h1>")
        .replace("\n## ", "</p><h2>")
        .replace("\n### ", "</p><h3>")
        .replace("\n\n", "</p><p>")
        .replace("```", "<pre><code>")
        .replace('`', "<code>")
        .replace("| ", "<td>")
        .replace(" |", "</td>")
        .replace("---\n", "</tr><tr>")
        .replace("**", "<strong>")
        .replace("- ", "<li>")
        .replace("\n</p>", "</p>");

    format!(
        r#"<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>ARES V3 Audit Report - {}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; line-height: 1.6; color: #333; }}
        h1 {{ color: #1a1a1a; border-bottom: 3px solid #e74c3c; padding-bottom: 10px; }}
        h2 {{ color: #2c3e50; margin-top: 30px; }}
        h3 {{ color: #e74c3c; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        th {{ background-color: #f5f5f5; font-weight: 600; }}
        tr:nth-child(even) {{ background-color: #fafafa; }}
        code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-family: 'SF Mono', Monaco, monospace; font-size: 0.9em; }}
        hr {{ border: none; border-top: 1px solid #eee; margin: 30px 0; }}
        pre {{ background: #f8f8f8; padding: 16px; border-radius: 4px; overflow-x: auto; }}
        p {{ margin: 0 0 16px 0; }}
    </style>
</head>
<body>
<div class="report">
{}
</div>
</body>
</html>"#,
        report.target.name, html_body
    )
}

/// Generate a GitHub issue template from an audit report.
pub fn generate_github_issue(report: &AuditReport) -> String {
    let mut issue = format!(
        "## Security Audit Findings for `{}`\n\n",
        report.target.name
    );

    issue.push_str("### Summary\n\n");
    issue.push_str(&format!(
        "- **Critical:** {}\n",
        report.summary.critical_count
    ));
    issue.push_str(&format!("- **High:** {}\n", report.summary.high_count));
    issue.push_str(&format!("- **Medium:** {}\n", report.summary.medium_count));
    issue.push_str(&format!("- **Low:** {}\n\n", report.summary.low_count));

    issue.push_str("### Findings\n\n");

    for finding in &report.findings {
        issue.push_str(&format!("#### `{}` — {}\n\n", finding.id, finding.title));
        issue.push_str(&format!("- **Severity:** {}\n", finding.severity));
        issue.push_str(&format!("- **Category:** {}\n", finding.category));
        issue.push_str(&format!(
            "- **Confidence:** {:.0}%\n",
            finding.confidence * 100.0
        ));
        issue.push_str(&format!("\n{}", finding.description));
        issue.push_str(&format!(
            "\n\n**Recommendation:** {}\n\n",
            finding.recommendation
        ));
        if let Some(ref poc) = finding.proof_of_concept {
            issue.push_str(&format!("**PoC:** `{:?}`\n\n", poc));
        }
        issue.push_str("---\n\n");
    }

    issue.push_str("### Environment\n\n");
    issue.push_str(&format!(
        "- **ARES Version:** {}\n",
        report.metadata.ares_version
    ));
    issue.push_str(&format!(
        "- **Scan Date:** {}\n",
        report.metadata.generated_at
    ));
    issue.push_str(&format!(
        "- **Pipeline:** {}\n",
        report.metadata.agent_pipeline.join(", ")
    ));
    issue.push_str(&format!(
        "- **Tools:** {}\n",
        report.metadata.tools_used.join(", ")
    ));
    issue.push_str("\n---\n\n*Reported by ARES V3 Autonomous Security Auditor*\n");

    issue
}

/// Estimate exploit value for a finding (simplified scorer).
fn estimate_exploit_value(finding: &Finding) -> u64 {
    let base = match finding.severity {
        Severity::Critical => 1_000_000_000u64,
        Severity::High => 500_000_000u64,
        Severity::Medium => 100_000_000u64,
        Severity::Low => 10_000_000u64,
        Severity::Informational => 1_000_000u64,
    };

    let confidence_dampener = (finding.confidence * 10.0).clamp(1.0, 10.0) as u64;
    let raw = base.saturating_mul(confidence_dampener) / 10;
    raw.min(10_000_000_000)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ares_core::{CodeLocation, ProgramTarget, ReportMetadata, ReportSummary};
    use chrono::Utc;

    fn sample_report() -> AuditReport {
        AuditReport {
            target: ProgramTarget {
                name: "test-program".to_string(),
                repository_url: None,
                commit_hash: None,
                program_id: None,
                source_path: std::path::PathBuf::from("."),
                idl_path: None,
            },
            findings: vec![Finding {
                id: "TEST-001".to_string(),
                title: "Missing signer check".to_string(),
                description: "Test description".to_string(),
                severity: Severity::High,
                category: ares_core::VulnerabilityCategory::SignerAuthorization,
                location: CodeLocation::default(),
                proof_of_concept: None,
                recommendation: "Add signer check".to_string(),
                references: vec![],
                confidence: 0.9,
            }],
            suppressed_findings: vec![],
            metadata: ReportMetadata {
                generated_at: Utc::now(),
                ares_version: "0.1.0".to_string(),
                scan_duration_secs: 5,
                agent_pipeline: vec!["regex".to_string(), "ast".to_string()],
                tools_used: vec!["ares-mapper".to_string()],
            },
            summary: ReportSummary {
                total_findings: 1,
                critical_count: 0,
                high_count: 1,
                medium_count: 0,
                low_count: 0,
                informational_count: 0,
                false_positives_suppressed: 0,
                poc_generated: 0,
                tests_passed: 0,
                tests_failed: 0,
                total_economic_impact_lamports: 450_000_000,
                max_single_exploit_lamports: 450_000_000,
            },
        }
    }

    #[test]
    fn test_markdown_report_contains_findings() {
        let report = sample_report();
        let md = generate_markdown(&report);
        assert!(md.contains("Missing signer check"));
        assert!(md.contains("TEST-001"));
        assert!(md.contains("Critical"));
    }

    #[test]
    fn test_html_report_is_valid() {
        let report = sample_report();
        let html = generate_html(&report);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("test-program"));
    }

    #[test]
    fn test_github_issue_format() {
        let report = sample_report();
        let issue = generate_github_issue(&report);
        assert!(issue.contains("Security Audit Findings"));
        assert!(issue.contains("Missing signer check"));
    }
}
